clear;
clc;

PsrGlobals  %define the global variable for useful parameter to be used in other program

[filename0, pathname] = uigetfile( ...
    {'*.dat','data Files';...
    '*.*','All Files' },...
    '请选择要处理的脉冲星数据',...
    'J:\存数软件');
if isequal(filename0,0)
   disp('User selected Cancel')
   return;
else
   filename= fullfile(pathname, filename0);
end

fp_r=fopen(filename,'r+');
[psr_head_info,len] = fread(fp_r,512,'uint8');%将512字节文件头读出来
 
sprintf('1-Version: %s\n2-Pulsar_Name: %s\n3-Observe_Time: %s\n8-Observe_Mode: %s\n9-Channel_Num: %s\n15-Start_Freq(MHz): %s\n16-Stop_Freq(MHz): %s\n17-Bandwidth(MHz): %s\n18-dt(ms): %s\n25-ACCNo: %s\n28-Start+CH: %s\n29-Stop_CH: %s\n',...
    psr_head_info(1:16),...
    psr_head_info(17:32),...
    psr_head_info(33:48),...
    psr_head_info(113:128),...
    psr_head_info(129:144),...
    psr_head_info(225:240),...
    psr_head_info(241:256),...
    psr_head_info(257:272),...
    psr_head_info(273:288),...
    psr_head_info(385:400),...
    psr_head_info(433:448),...
    psr_head_info(449:464))

str = zeros(1,16);
sel = input('sel num(-1：QUIT) = ');
while(sel >0)
if(sel==1 || sel == 2 || sel ==3 || sel == 8 || sel == 9 || sel == 15 || sel == 16 || sel == 17 || sel == 18 || sel == 25 || sel == 28 || sel == 29)
    str = input('Modify Value:','s');
    psr_head_info(((sel-1)*16+1):(sel*16)) = zeros(16,1);
    len = length(str);
    for i = 1:len
        psr_head_info((sel-1)*16+i) = str(i);
    end
else
    sprintf('Error\n');
end
    sel = input('sel num(-1：QUIT) = ');
end

sprintf('1-Version: %s\n2-Pulsar_Name: %s\n3-Observe_Time: %s\n8-Observe_Mode: %s\n9-Channel_Num: %s\n15-Start_Freq(MHz): %s\n16-Stop_Freq(MHz): %s\n17-Bandwidth(MHz): %s\n18-dt(ms): %s\n25-ACCNo: %s\n28-Start_CH: %s\n29-Stop_CH: %s\n',...
    psr_head_info(1:16),...
    psr_head_info(17:32),...
    psr_head_info(33:48),...
    psr_head_info(113:128),...
    psr_head_info(129:144),...
    psr_head_info(225:240),...
    psr_head_info(241:256),...
    psr_head_info(257:272),...
    psr_head_info(273:288),...
    psr_head_info(385:400),...
    psr_head_info(433:448),...
    psr_head_info(449:464))

fseek(fp_r,0,'bof');
fwrite(fp_r,psr_head_info,'uint8');
fclose(fp_r);