% parameters from psf header
global SourceName...
       SaveTime...
       Observer...
       ObsDate...
       ObsTime...
       Receiver...
       ObsMode...
       ChannelNum...
       VgaGainL...
       VgaGainR...
       LScale...
       RScale...
       DigitalGain...
       ObsStartFreq...
       ObsCenterFreq...
       ObsBandwidth...
       SamplingTime...
       Az...
       El...
       Ra...
       Dec...
       SamplingFreq...
       FFTNum...
       AccNum...
       PPSResetTime...
       BitMode...
       StartCh...
       StopCh...
       CenterFreq...
       SideBand

% calculated parameters
global DataType FrameHeaderSize FrameLen

% lost frames
global TotalLost TimeInfoPrevious TimeInfoNext

% read FrameNum frames from psf file one time for data processing
global FrameNumOneTime PsfDataBuf PsfTimeInfoBuf PsfDataCnt PsfPointer
